services:
  postgres:
    image: postgres:15
    container_name: postgres_ptdm
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./ptdm_backend
      dockerfile: WebAPI/Dockerfile
    container_name: ptdm_backend
    # Exposing 8080 locally for direct access if needed
    ports:
      - "5175:5175"
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=${POSTGRES_PORT:-5432};Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./ptdm_react
      dockerfile: Dockerfile
    container_name: ptdm_frontend
    # Exposing 3000 locally as an alternative to nginx
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: ptdm_gateway
    ports:
      - "3372:80"
      - "5215:5175"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend