services:
  backend:
    image: leoncoutinho1/ptdm-backend:latest
    container_name: ptdm_backend
    restart: always
    ports:
      - "5175:5175"
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=${POSTGRES_DB:-ptdm};User Id=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres};
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=5175
      - PORT=5175

  frontend:
    image: leoncoutinho1/ptdm-frontend:latest
    container_name: ptdm_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
